# schemas.py
# JSON Schema definitions for Pet and Order API responses based on app.py

# --------------------------------------------
# Pet schema
# --------------------------------------------
pet = {
    "type": "object",
    "required": ["id", "name", "type", "status"],
    "properties": {
        "id": {"type": "integer"},
        "name": {"type": "string"},  # Bug fixed changed the as string from integer
        "type": {
            "type": "string",
            "enum": ["cat", "dog", "fish"]
        },
        "status": {
            "type": "string",
            "enum": ["available", "pending", "sold"]
        }
    }
}

# Pets list schema
pets_list = {
    "type": "array",
    "items": pet
}

# --------------------------------------------
# Order schema
# --------------------------------------------
order = {
    "type": "object",
    "required": ["id", "pet_id"],
    "properties": {
        "id": {"type": "string"},  # UUID generated by app.py
        "pet_id": {"type": "integer"}
    }
}

# PATCH /store/order/<order_id> response
patch_order_response = {
    "type": "object",
    "required": ["message"],
    "properties": {
        "message": {"type": "string"}
    }
}